name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub 
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Push Docker image
      run: | 
        docker push ${{ secrets.DOCKER_USERNAME }}/hello_world:latest

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      # Step 5: Set up SSH
#      - name: Set up SSH
#        uses: webfactory/ssh-agent@v0.8.1
#        with:
#          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
#
#      # Step 6: Pull and run the Docker image on the server
#      - name: Deploy on server
#        run: |
#          ssh -o StrictHostKeyChecking=no user@your-server-ip << 'EOF'
#            docker pull ${{ secrets.DOCKER_USERNAME }}/my-app:latest
#            docker stop my-app || true
#            docker rm my-app || true
#            docker run -d --name my-app -p 80:80 ${{ secrets.DOCKER_USERNAME }}/my-app:latest
#          EOF